TICKER = "AAPL"
PERIOD = "2y"

CANDLE_WIDTH = 0.5
RANGE_CANDLE = 15

SHOW_PD = True
SHOW_BEARISH_BOS = True
SHOW_BULLISH_BOS = True

BULLISH_OB_COLOUR = "rgba(0,255,0,0.35)"
BEARISH_OB_COLOUR = "rgba(255,0,0,0.35)"
